name: publish_image
description: Builds and pushs image

inputs: 
  dockerhub_username: 
    description: 'Dockerhub username'
    required: true
    type: text
  dockerhub_password: 
    description: 'Dockerhub password'
    required: true
    type: text
  postgres:
    description: 'PostgreSQL version'
    required: true
    type: text
  hll:
    description: 'HLL plugin version'
    required: true
    default: '2.17'
    type: text
  dockerfile:
    description: 'Dockerfile used on build'
    required: true
    default: 'Dockerfile.debian'
    type: text
  main_tag:
    description: 'Maint tag that shouldbe used'
    required: true
    type: text
  tags:
    description: 'All tags that should be used'
    required: true
    type: text
  platforms:
    description: 'All platforms that the image should be built'
    required: true
    type: text
  

runs:
  using: "composite"
  steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./${{ inputs.dockerfile }}
        build-args: |
          POSTGRES_VERSION=${{ inputs.postgres }}
          HLL_VERSION=${{ inputs.hll }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ inputs.tags }}
        cache-from: type=registry,ref=${{ inputs.main_tag }}
        cache-to: type=inline