name: publish_all

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  update-description:
    concurrency:
        group: update-description
        cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: hbontempo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: hbontempo/postgres-hll
          short-description: "Development PostgreSQL images with the HyperLogLog extension"

  get_configuration_files:
    uses: ./.github/workflows/configuration_files.yml

  publish:
    needs: get_configuration_files
    strategy:
      fail-fast: false
      matrix: 
        config_file: ${{ fromJson(needs.get_configuration_files.outputs.matrix) }}
    uses: ./.github/workflows/publish.yml
    with:
      image_name: hbontempo/postgres-hll
      config_file: ${{ matrix.config_file }}
    secrets: inherit
